package storage

import (
	"context"
	"errors"
	"fmt"
	"math/big"
	"sort"

	"github.com/ethereum/go-ethereum/common"

	"github.com/strahe/synapse-go/spregistry"
	"github.com/strahe/synapse-go/types"
	"github.com/strahe/synapse-go/warmstorage"
)

// PDPProviderSource is the subset of spregistry.Service used by ServiceResolver.
type PDPProviderSource interface {
	GetPDPProvider(context.Context, types.ProviderID) (*spregistry.PDPProvider, error)
	SelectActivePDPProviders(context.Context, spregistry.ProviderFilter) ([]spregistry.PDPProvider, error)
}

// DataSetCatalog is the subset of warmstorage.Service used by ServiceResolver.
type DataSetCatalog interface {
	GetApprovedProviderIDs(context.Context, types.ListOptions) ([]types.ProviderID, error)
	GetClientDataSets(context.Context, common.Address, types.ListOptions) ([]*warmstorage.DataSetInfo, error)
	GetDataSet(context.Context, types.DataSetID) (*warmstorage.DataSetInfo, error)
	GetAllDataSetMetadata(context.Context, types.DataSetID) (map[string]string, error)
}

// ResolvedUploadContext is the pre-selection result for one provider copy.
type ResolvedUploadContext struct {
	Provider        Provider
	DataSetID       *types.DataSetID      // nil when a new data set will be created
	ClientDataSetID types.ClientDataSetID // stable caller-chosen ID reused across commits; nil for new datasets (auto-generated by PresignForCommit)
	DataSetMetadata map[string]string     // metadata carried into the new data set if created
}

// ContextFactory builds an UploadContext from a resolved selection.
type ContextFactory func(ResolvedUploadContext, *UploadOptions) (UploadContext, error)

// ServiceResolverOptions configures a ServiceResolver.
type ServiceResolverOptions struct {
	Payer       common.Address // EVM address of the paying account
	SPRegistry  PDPProviderSource
	WarmStorage DataSetCatalog
	NewContext  ContextFactory // called per-provider to construct an UploadContext
}

// ServiceResolver selects providers and data sets for each upload, reusing
// existing data sets when metadata matches exactly.
type ServiceResolver struct {
	payer       common.Address
	spRegistry  PDPProviderSource
	warmStorage DataSetCatalog
	newContext  ContextFactory
}

var (
	_ PDPProviderSource = (*spregistry.Service)(nil)
	_ DataSetCatalog    = (*warmstorage.Service)(nil)
)

// NewServiceResolver constructs a ServiceResolver. All fields in opts are required.
func NewServiceResolver(opts ServiceResolverOptions) (*ServiceResolver, error) {
	if opts.Payer == (common.Address{}) {
		return nil, fmt.Errorf("storage.NewServiceResolver: %w: zero payer", ErrInvalidArgument)
	}
	if opts.SPRegistry == nil {
		return nil, fmt.Errorf("storage.NewServiceResolver: %w: nil SPRegistry", ErrInvalidArgument)
	}
	if opts.WarmStorage == nil {
		return nil, fmt.Errorf("storage.NewServiceResolver: %w: nil WarmStorage", ErrInvalidArgument)
	}
	if opts.NewContext == nil {
		return nil, fmt.Errorf("storage.NewServiceResolver: %w: nil NewContext", ErrInvalidArgument)
	}
	return &ServiceResolver{
		payer:       opts.Payer,
		spRegistry:  opts.SPRegistry,
		warmStorage: opts.WarmStorage,
		newContext:  opts.NewContext,
	}, nil
}

// ResolveUploadContexts returns one UploadContext per requested copy. When
// neither ProviderIDs nor DataSetIDs are set, providers are auto-selected from
// the warmstorage-approved and active-PDP intersection. The second return value
// is true when providers were explicitly specified by opts.
func (r *ServiceResolver) ResolveUploadContexts(ctx context.Context, opts *UploadOptions) ([]UploadContext, bool, error) {
	selections, explicit, err := r.resolveSelections(ctx, opts, nil)
	if err != nil {
		return nil, false, err
	}
	contexts := make([]UploadContext, 0, len(selections))
	for _, selection := range selections {
		uploadCtx, err := r.newContext(selection, opts)
		if err != nil {
			return nil, false, fmt.Errorf("storage.ServiceResolver.ResolveUploadContexts: build context for provider %d: %w", uint64(selection.Provider.ID), err)
		}
		contexts = append(contexts, uploadCtx)
	}
	return contexts, explicit, nil
}

// SelectReplacement picks a single unused provider to replace a failed attempt.
func (r *ServiceResolver) SelectReplacement(ctx context.Context, usedProviders map[types.ProviderID]struct{}, opts *UploadOptions) (UploadContext, error) {
	selections, _, err := r.resolveSelections(ctx, withCopies(opts, 1), usedProviders)
	if err != nil {
		return nil, err
	}
	if len(selections) == 0 {
		return nil, errors.New("storage.ServiceResolver.SelectReplacement: no remaining providers")
	}
	uploadCtx, err := r.newContext(selections[0], opts)
	if err != nil {
		return nil, fmt.Errorf("storage.ServiceResolver.SelectReplacement: build context for provider %d: %w", uint64(selections[0].Provider.ID), err)
	}
	return uploadCtx, nil
}

func (r *ServiceResolver) resolveSelections(ctx context.Context, opts *UploadOptions, extraExcludes map[types.ProviderID]struct{}) ([]ResolvedUploadContext, bool, error) {
	if opts == nil {
		opts = &UploadOptions{}
	}
	switch {
	case len(opts.DataSetIDs) > 0:
		resolved, err := r.resolveByDataSetIDs(ctx, opts)
		return resolved, true, err
	case len(opts.ProviderIDs) > 0:
		resolved, err := r.resolveByProviderIDs(ctx, opts)
		return resolved, true, err
	default:
		resolved, err := r.autoSelect(ctx, opts, extraExcludes)
		return resolved, false, err
	}
}

func (r *ServiceResolver) resolveByDataSetIDs(ctx context.Context, opts *UploadOptions) ([]ResolvedUploadContext, error) {
	ids := dedupeIDs(opts.DataSetIDs)
	count := opts.Copies
	if count == 0 {
		count = len(ids)
	}
	if len(ids) != count {
		return nil, fmt.Errorf("storage.ServiceResolver.ResolveUploadContexts: requested %d context(s) but dataSetIDs resolved to %d after deduplication", count, len(ids))
	}

	out := make([]ResolvedUploadContext, 0, len(ids))
	seenProviders := map[types.ProviderID]struct{}{}
	for _, dataSetID := range ids {
		dataSet, err := r.warmStorage.GetDataSet(ctx, dataSetID)
		if err != nil {
			if errors.Is(err, warmstorage.ErrNotFound) {
				return nil, fmt.Errorf("storage.ServiceResolver.ResolveUploadContexts: data set %d does not exist", uint64(dataSetID))
			}
			return nil, fmt.Errorf("storage.ServiceResolver.ResolveUploadContexts: get data set %d: %w", uint64(dataSetID), err)
		}
		if dataSet.Payer != r.payer {
			return nil, fmt.Errorf("storage.ServiceResolver.ResolveUploadContexts: data set %d is not owned by %s", uint64(dataSetID), r.payer.Hex())
		}
		if dataSet.PDPEndEpoch != 0 {
			return nil, fmt.Errorf("storage.ServiceResolver.ResolveUploadContexts: data set %d is not active", uint64(dataSetID))
		}
		provider, err := r.spRegistry.GetPDPProvider(ctx, dataSet.ProviderID)
		if err != nil {
			if errors.Is(err, spregistry.ErrNotFound) {
				return nil, fmt.Errorf("storage.ServiceResolver.ResolveUploadContexts: provider %d for data set %d not found", uint64(dataSet.ProviderID), uint64(dataSetID))
			}
			return nil, fmt.Errorf("storage.ServiceResolver.ResolveUploadContexts: get provider %d: %w", uint64(dataSet.ProviderID), err)
		}
		if _, ok := seenProviders[provider.Info.ID]; ok {
			return nil, errors.New("storage.ServiceResolver.ResolveUploadContexts: dataSetIDs resolve to duplicate providers")
		}
		seenProviders[provider.Info.ID] = struct{}{}
		metadata, err := r.warmStorage.GetAllDataSetMetadata(ctx, dataSetID)
		if err != nil {
			return nil, fmt.Errorf("storage.ServiceResolver.ResolveUploadContexts: get data set metadata %d: %w", uint64(dataSetID), err)
		}
		dsID := dataSetID
		out = append(out, buildResolvedUploadContext(*provider, &dsID, dataSet.ClientDataSetID, metadata))
	}
	return out, nil
}

func (r *ServiceResolver) resolveByProviderIDs(ctx context.Context, opts *UploadOptions) ([]ResolvedUploadContext, error) {
	ids := dedupeIDs(opts.ProviderIDs)
	count := opts.Copies
	if count == 0 {
		count = len(ids)
	}
	if len(ids) != count {
		return nil, fmt.Errorf("storage.ServiceResolver.ResolveUploadContexts: requested %d context(s) but providerIDs resolved to %d after deduplication", count, len(ids))
	}

	dataSets, err := r.warmStorage.GetClientDataSets(ctx, r.payer, types.ListOptions{})
	if err != nil {
		return nil, fmt.Errorf("storage.ServiceResolver.ResolveUploadContexts: get client data sets: %w", err)
	}
	requestedMetadata := dataSetMetadataFromOptions(opts)
	out := make([]ResolvedUploadContext, 0, len(ids))
	for _, providerID := range ids {
		provider, err := r.spRegistry.GetPDPProvider(ctx, providerID)
		if err != nil {
			if errors.Is(err, spregistry.ErrNotFound) {
				return nil, fmt.Errorf("storage.ServiceResolver.ResolveUploadContexts: provider %d not found", uint64(providerID))
			}
			return nil, fmt.Errorf("storage.ServiceResolver.ResolveUploadContexts: get provider %d: %w", uint64(providerID), err)
		}
		dataSetID, clientDataSetID, metadata, err := r.selectMatchingDataSet(ctx, providerID, dataSets, requestedMetadata)
		if err != nil {
			return nil, err
		}
		out = append(out, buildResolvedUploadContext(*provider, dataSetID, clientDataSetID, metadata))
	}
	return out, nil
}

func (r *ServiceResolver) autoSelect(ctx context.Context, opts *UploadOptions, extraExcludes map[types.ProviderID]struct{}) ([]ResolvedUploadContext, error) {
	count := opts.Copies
	if count == 0 {
		count = 2
	}
	approvedIDs, err := r.warmStorage.GetApprovedProviderIDs(ctx, types.ListOptions{})
	if err != nil {
		return nil, fmt.Errorf("storage.ServiceResolver.ResolveUploadContexts: get approved providers: %w", err)
	}
	if len(approvedIDs) == 0 {
		return nil, errors.New("storage.ServiceResolver.ResolveUploadContexts: no approved providers")
	}
	excludeIDs := appendExcludedIDs(opts.ExcludeProviderIDs, extraExcludes)
	providers, err := r.spRegistry.SelectActivePDPProviders(ctx, spregistry.ProviderFilter{ExcludeIDs: excludeIDs})
	if err != nil {
		return nil, fmt.Errorf("storage.ServiceResolver.ResolveUploadContexts: select active PDP providers: %w", err)
	}
	approvedSet := make(map[types.ProviderID]struct{}, len(approvedIDs))
	for _, id := range approvedIDs {
		approvedSet[id] = struct{}{}
	}

	dataSets, err := r.warmStorage.GetClientDataSets(ctx, r.payer, types.ListOptions{})
	if err != nil {
		return nil, fmt.Errorf("storage.ServiceResolver.ResolveUploadContexts: get client data sets: %w", err)
	}
	requestedMetadata := dataSetMetadataFromOptions(opts)
	withDataSet := make([]ResolvedUploadContext, 0, len(providers))
	withoutDataSet := make([]ResolvedUploadContext, 0, len(providers))
	for _, provider := range providers {
		if _, ok := approvedSet[provider.Info.ID]; !ok {
			continue
		}
		dataSetID, clientDataSetID, metadata, err := r.selectMatchingDataSet(ctx, provider.Info.ID, dataSets, requestedMetadata)
		if err != nil {
			return nil, err
		}
		resolved := buildResolvedUploadContext(provider, dataSetID, clientDataSetID, metadata)
		if dataSetID != nil {
			withDataSet = append(withDataSet, resolved)
		} else {
			withoutDataSet = append(withoutDataSet, resolved)
		}
	}

	selected := make([]ResolvedUploadContext, 0, len(withDataSet)+len(withoutDataSet))
	selected = append(selected, withDataSet...)
	selected = append(selected, withoutDataSet...)
	if len(selected) > count {
		selected = selected[:count]
	}
	if len(selected) == 0 {
		return nil, errors.New("storage.ServiceResolver.ResolveUploadContexts: no remaining providers")
	}
	return selected, nil
}

func (r *ServiceResolver) selectMatchingDataSet(ctx context.Context, providerID types.ProviderID, dataSets []*warmstorage.DataSetInfo, requestedMetadata map[string]string) (*types.DataSetID, types.ClientDataSetID, map[string]string, error) {
	matching := make([]*warmstorage.DataSetInfo, 0)
	for _, dataSet := range dataSets {
		if dataSet == nil {
			continue
		}
		if dataSet.DataSetID == 0 || dataSet.ProviderID != providerID || dataSet.PDPEndEpoch != 0 {
			continue
		}
		matching = append(matching, dataSet)
	}
	sort.Slice(matching, func(i, j int) bool {
		return matching[i].DataSetID < matching[j].DataSetID
	})
	// TODO: N+1 RPC calls — one GetAllDataSetMetadata per candidate dataset.
	// Batch metadata fetch would require a new server API endpoint.
	for _, dataSet := range matching {
		metadata, err := r.warmStorage.GetAllDataSetMetadata(ctx, dataSet.DataSetID)
		if err != nil {
			return nil, nil, nil, fmt.Errorf("storage.ServiceResolver.ResolveUploadContexts: get data set metadata %d: %w", uint64(dataSet.DataSetID), err)
		}
		if metadataMatches(metadata, requestedMetadata) {
			dsID := dataSet.DataSetID
			return &dsID, copyClientDataSetID(dataSet.ClientDataSetID), metadata, nil
		}
	}
	return nil, nil, cloneStringMap(requestedMetadata), nil
}

func buildResolvedUploadContext(provider spregistry.PDPProvider, dataSetID *types.DataSetID, clientDataSetID types.ClientDataSetID, metadata map[string]string) ResolvedUploadContext {
	return ResolvedUploadContext{
		Provider: Provider{
			ID:              provider.Info.ID,
			ServiceURL:      provider.Offering.ServiceURL,
			ServiceProvider: provider.Info.ServiceProvider,
			Payee:           provider.Info.Payee,
		},
		DataSetID:       copyIDPtr(dataSetID),
		ClientDataSetID: copyClientDataSetID(clientDataSetID),
		DataSetMetadata: cloneStringMap(metadata),
	}
}

func metadataMatches(dataSetMetadata, requestedMetadata map[string]string) bool {
	if len(dataSetMetadata) != len(requestedMetadata) {
		return false
	}
	for key, value := range requestedMetadata {
		if dataSetMetadata[key] != value {
			return false
		}
	}
	return true
}

func dataSetMetadataFromOptions(opts *UploadOptions) map[string]string {
	metadata := cloneStringMap(opts.DataSetMetadata)
	if opts.WithCDN {
		if metadata == nil {
			metadata = make(map[string]string, 1)
		}
		metadata["withCDN"] = ""
	}
	return metadata
}

func withCopies(opts *UploadOptions, copies int) *UploadOptions {
	if opts == nil {
		return &UploadOptions{Copies: copies}
	}
	cloned := *opts
	cloned.Copies = copies
	if len(opts.PieceMetadata) != 0 {
		cloned.PieceMetadata = cloneStringMap(opts.PieceMetadata)
	}
	if len(opts.DataSetMetadata) != 0 {
		cloned.DataSetMetadata = cloneStringMap(opts.DataSetMetadata)
	}
	if len(opts.ProviderIDs) != 0 {
		cloned.ProviderIDs = append([]types.ProviderID(nil), opts.ProviderIDs...)
	}
	if len(opts.DataSetIDs) != 0 {
		cloned.DataSetIDs = append([]types.DataSetID(nil), opts.DataSetIDs...)
	}
	if len(opts.ExcludeProviderIDs) != 0 {
		cloned.ExcludeProviderIDs = append([]types.ProviderID(nil), opts.ExcludeProviderIDs...)
	}
	return &cloned
}

func appendExcludedIDs(excluded []types.ProviderID, extra map[types.ProviderID]struct{}) []types.ProviderID {
	out := append([]types.ProviderID(nil), excluded...)
	seen := make(map[types.ProviderID]struct{}, len(out))
	for _, id := range out {
		seen[id] = struct{}{}
	}
	for id := range extra {
		if _, ok := seen[id]; ok {
			continue
		}
		seen[id] = struct{}{}
		out = append(out, id)
	}
	return out
}

func dedupeIDs[T comparable](values []T) []T {
	if len(values) == 0 {
		return nil
	}
	out := make([]T, 0, len(values))
	seen := make(map[T]struct{}, len(values))
	for _, value := range values {
		if _, ok := seen[value]; ok {
			continue
		}
		seen[value] = struct{}{}
		out = append(out, value)
	}
	return out
}

func copyIDPtr[T ~uint64](v *T) *T {
	if v == nil {
		return nil
	}
	cp := *v
	return &cp
}

func copyClientDataSetID(v types.ClientDataSetID) types.ClientDataSetID {
	if v == nil {
		return nil
	}
	return new(big.Int).Set(v)
}
